{% set name = "PubChemPy" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 08f0b2a82a5caa5d61e14935d655da554602d7b5686fe661ab584c882ffff623

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=0.16.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pubchempy

about:
  home: https://github.com/mcs07/PubChemPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python wrapper for the PubChem PUG REST API.'

extra:
  recipe-maintainers:
    - mcs07
    - hadim
